### ISSUE TITLE
Regression tests consistently time out on s390x with Hotspot JDK8

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#1051]
Following tests got timeout issue on 390x with Hotpot JDK8 ( works fine with Openj9 JDK8)

java/math/BigInteger/LargeValueExceptions.java
java/security/KeyPairGenerator/SolarisShortDSA.java
java/security/MessageDigest/TestDigestIOStream.java.
java/util/Arrays/TimSortStackSize2.java
java/util/Random/RandomTest.java.
java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java
java/util/stream/boottest/java/util/stream/SpinedBufferTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/CountLargeTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/ExplodeOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/SequentialOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java
sun/nio/ch/TestMaxCachedBufferSize.java
sun/nio/cs/OLD/TestIBMDB.java

```
12:28:09  TEST RESULT: Error. Program `/data/jenkins/workspace/openjdk8_hs_openjdktest_s390x_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960438ms).
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_s390x_linux/18/

**Comment by sophia-guo** [comment]
Tried with timeout factor increased got the same failure.

**Comment by adamfarley** [comment]
Another significant test is TestAESMain. It runs for a minute or two on other platforms + release versions, but runs for over 6 hours on zLinux. It doesn't fail, somehow, it just runs for 6+ hours and then passes.

Will exclude: (Add Exclusion PR link here)

@sophia-guo - Since zLinux doesn't appear to be an officially-supported build platform for jdk8 on Hotspot (as per the link below), can you see a reason that we should prioritize this test's diagnosis and repair?

https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms

**Comment by sxa** [comment]
*TestAESMain*: `time make _jdk_custom JDK_CUSTOM_TARGET=test/compiler/7184394/TestAESMain.java`
- JDK8/J9: 2m45
- JDK8/J9 -Xint: At the time of writing it's been running for over an hour
- JDK11/HS: 2m47
- JDK11/HS -Xint: 
- JDK8/HS: Presumably the 6h you've seen fromte job

I may not bother filling in the details of the "blanks" above - looks fairly conclusive that the slowdown on HotSpot JDK8 is due to the (lack of) JIT. If the test cannot be parameterised I would definitely suggest excluding it on this platform.

**Comment by adamfarley** [comment]
Now that the 6hr test is excluded, here's a long run to create a current list of failing + excessively-long unit tests:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_extended.openjdk_s390x_linux/20/console

However, this may not be needed if we stop running testing on JDK8 Hotspot zLinux builds:
https://github.com/AdoptOpenJDK/TSC/issues/218

**Comment by smlambert** [comment]
Closing this.  We have decided to reduce testing on this platform/impl/version as it has no JIT.
