### ISSUE TITLE
openjdk.regression suite fails for version javaNext

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1176]
The getOpenJDK build task tries to get github.com:ibmruntimes/openj9-openjdk-jdknext or 13
rather than just openj9-openjdk-jdk

**Comment by smlambert** [comment]
The flow of events...  
1) you want to run tests, but not explicitly say what version...  you set some environment variables:
JDK_VERSION="next" 
TEST_JDK_HOME=/someJdk13

2) Since JDK_VERSION=next is a conceptual idea, not something that exists or that can be used to compile code, Test system tries to AUTO_DETECT the version of the JDK found at TEST_JDK_HOME. It determines that it is jdk13, where we subsequently set JDK_VERSION=13

3) At the point where we try to clone the openj9-openjdk-jdk repo, we are looking for 13, but you have not yet created a repo called openj9-openjdk-jdk13, you are continuing to use openj9-openjdk-jdk. 
 Presumably, openj9-openjdk-jdk13 only gets created at such a time as 14 becomes next...  

A couple of options to work around this:
a) if we can not find the existence of a particular versioned repo, we drop to a default of pulling openj9-openjdk-jdk

alternatively 
b) we carry forward an additional variable to pass to the build.xml / compile stage indicating the JCL is of version "next"... perhaps we can reclaim the JCL_VERSION env var, now that we no longer require it to indicate past ("current") and present ("latest") JCLs, but now use to indicate future ("next")

**Comment by smlambert** [comment]
@andrew-m-leonard - is it sufficient / safe for us to assume to use openj9-openjdk-jdk repo if no versioned repo exists?   (option a above)

**Comment by smlambert** [comment]
closed by #1257
