### ISSUE TITLE
Diagnostic files not being archived as expected with test_output

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1193]
There have been 2 reports of core files generated from openjdk test crashes not getting archived.  We believe this functionality should work when ARCHIVE_TEST_RESULTS is selected in a Grinder job (https://github.com/AdoptOpenJDK/openjdk-tests/pull/1073), but we should investigate why it is not.

**Comment by sophia-guo** [comment]
We currently set jtreg tests as only retain files generated by test that fail or cause error. That is if test pass and no error all generated files will be deleted after each test completes executing. 

Some special case is there are system dump generated by passing tests, which dump files will be deleted. In order to keep those file we can update to retain those files by using file name pattern.

**Comment by smlambert** [comment]
Good catch, the 2 cases that were reported through Slack are when tests report as passed (but a crash is still seen).

**Comment by sophia-guo** [comment]
Interesting, even if set with option to retain files that match a specific filename there is no those files under that specific folder described on console output 'tests/TestConfig/test_output_15613907978889/jdk_util_0/work/scratch/4/core.20190624.114421.14985.0001.dmp'

**Comment by sophia-guo** [comment]
Actually scratch directory is a tmp directory for the running test, which is used to write any temporary files. Jtreg will ensure that the directory is always empty when the test begins. So we cannot expect dump or other files stay there.

The corresponding dmp files can actually be found per tests.

**Comment by sophia-guo** [comment]
So two notes here

1. Will update code to make sure even if tests pass still retain those dmp files
2. Instead of finding the files under scratch please find them per tests
