### ISSUE TITLE
OpenJDK regression test results not reported for some tests

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1423]
Some tests, including the two listed below, *should* be run as part of the OpenJDK11 Sanity regression bucket, as they are included in jdk_math.

jdk/java/math/BigInteger/SymmetricRangeTests.java
jdk/java/lang/invoke/LFCaching/LFGarbageCollectedTest.java

However, these tests are not reported as having run at all, and a local run shows that they run and fail with a specific error:

```
test result: Error. Parse Exception: `@library' must appear before first action tag
```

Since these tests don't appear to be excluded in a problem list, one possibility is that they are being run, but that errors of this type are simply "omitted" from the test results in Jenkins (TAP Results), along with any evidence that the test tried to run at all.

If this is correctly lumped in with other errors, such as the ones regarding machines not having enough memory when a hard minimum is specified in the test annotations, then the omission could be deliberate.

If this is not deliberate, then it appears to be a bug, and should be fixed if someone finds time.

**Comment by smlambert** [comment]
As per my note in Slack, I would have preferred you do some further investigation before raising this issue.  

Here is my investigation:

Error indicates problem with the jtreg annotations at the top of the test file.  When I looked, I noticed that both tests also have an `@ignore` tag.  Suspect test is present but being instructed to be skipped by the @ignore tag due to memory requirements (for SymmetricRangeTests)

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/jdk/java/math/BigInteger/SymmetricRangeTests.java#L26-L27

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/jdk/java/lang/invoke/LFCaching/LFGarbageCollectedTest.java#L28 - this test is ignored and associated with this [JDK-8078602 issue](https://bugs.openjdk.java.net/browse/JDK-8078602) according to the annotation

the @ignore tag means run the test but ignore results - so it may be entirely possible that the junit output created by jtreg does not flag it as a failure.  

From http://openjdk.java.net/jtreg/command-help.html, while it raises an error by default, I suspect jtreg does not consider it a real failure and therefore does not create junit xml file that indicates a failed test (or error).

<img width="529" alt="Screen Shot 2019-11-01 at 1 39 10 PM" src="https://user-images.githubusercontent.com/2836948/68044457-c23f9780-fcad-11e9-9b80-9684de450f0e.png">

To see what was actually happening I ran the jdk_math group in a Grinder, and it does not even include the BigInteger/SymmetricRangeTests.java - is this because of the `@ignore` tag?  

Please find out what the expected behaviour of jtreg is and report back.  Looks like ignored tests do not get included in top level make openjdk make targets (this is happening in the upstream tools, not testkitgen).  I suspect we would have to change the `@ignore` to `@ignore:run` to have it be included and run by jtreg.

**Comment by adamfarley** [comment]
As per the "-ignore:quiet" option, which is used in the ci command used to execute the jdk_math tests, Shelley's clip from the jtreg documentation implies that this test is ignored in our ci sanity runs deliberately.

Since this test omission is deliberate, this is not a bug, and will be closed.
