### ISSUE TITLE
Add maxDays to Artifactory buildInfo

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#1435]
Currently the test artifacts use only maxBuilds. There is another field for maxDays which, when specified, will allow the server to automatically cleanup old artifacts that are older than maxDays. The limitation of using only maxBuilds is when that particular build stops running (jdk12 for example), then there will be "maxBuilds" of artifacts left behind that will not get cleaned up automatically.

I just added this [change](https://github.com/eclipse/openj9/pull/7708/files) to OpenJ9 compiles and I would be willing to add it the test pipelines if this is something we're interested in.

Doc: https://www.jfrog.com/confluence/display/RTF/Scripted+Pipeline+Syntax
eg.
```
buildInfo.retention maxDays: 7
```

**Comment by smlambert** [comment]
Consciously chose to use only maxBuilds.  

IMHO, the purpose of setting maximums is to make sure we don't exceed a certain amount of storage on Jenkins, not to drop things after a week or a month.  If we use maxDays, we are throwing out information that could potentially be helpful, when its not required to throw out due to hitting an upper limit on storage.

**Comment by AdamBrousseau** [comment]
I see the concern. I think it's a trade-off between options. A) Set expiry dates on artfacts & manually protect anything you want kept. B) Don't set expiry but have some manual cleanup effort a few times a year. I think `B` is a much lower risk. It may be something we could make optional so that it can be set on a per farm or per build basis (eg. personal/grinder vs release vs nightly). I'm fine to leave as is for now but I may re-raise my concern once storage is a concern on some of our farms.
