### ISSUE TITLE
Add ability to pass ADDITIONAL jenkins label

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#1445]
Currently we can override the `LABEL` parameter with a non-default value which is useful. It would also be useful to be able to add a label in order to append to the default values. This would allow us to further narrow down the type of machine we want to pickup.

One option is to add another parameter called `LABEL_ADDITION`. My preference however would be to extend this ability to the current LABEL parameter. For example, if a user input `LABEL='&&<MY_LABEL>'`, the pipelines would recognize the special characters and append rather than replace. This could also be extended to `||` if desired.

**Comment by AdamBrousseau** [comment]
cc @jdekonin @vsebe 

We were thinking we could assign this to @jennychenyj if this is something the test maintainers were on-board with.

**Comment by smlambert** [comment]
Is there a reason why you would not just over-ride the entire label using the already existing LABEL param?  In other words, manage the 'append' on your top-level pipeline side of the pipeline and pass LABEL to test script?  This seems to make as

**Comment by AdamBrousseau** [comment]
I think the number one use case is our internal farm where we have multiple projects using the same Jenkins instance. We have project labels (eg. `ci.project.openj9`). It would be much easier for the top level pipeline to add a label to all the test builds rather than come up with logic to figure out all the labels for each platform. The test pipelines already have good defaults (eg `ci.role.test&&hw.arch.x86&&sw.os.linux`) so I believe it's easier to simply add a label to this list. Additionally, if the defaults change on the test side, and we go down the route of overriding, we may have label drift if we continue to use an "old" label.

**Comment by smlambert** [comment]
For that specific use case, is there a reason to keep the ci.role.test label on the non ci.project.openj9 machines ?

**Comment by AdamBrousseau** [comment]
Yes, as a specific example, `ci.peoject.ibm` would be added to a slightly different pool of zlinux machines than `ci.project.openj9` based on OS versions. OpenJ9 currently compiles on Ubuntu16 whereas IBM compiles on RHEL6 (iirc) which has a lower glibc level. As a result, an OpenJ9 sdk (test) will not run on RHEL6 whereas an IBM sdk (test) would. Therefore we would add the OpenJ9 project label to a subset of the machines we add the IBM project label and would need to direct the test builds accordingly.

**Comment by smlambert** [comment]
Currently our API works like this, either give us:

1.  a complete LABEL, or

1.  no LABEL (and we will figure out what label to use based on other parameters).  

Your proposal is to change our API to give us a partial LABEL that we append to the one we figure out.  

While it addresses the specific example, I believe this would introduce a lot of potential problems and 'muddy' our API.  This is why I suggested you calculate the label you need and pass us an entire label (case 1 above).

I think there are other ways to address your specific example as well.  We can discuss this week.

**Comment by smlambert** [comment]
So to capture some additional info on this one, there are a few points to consider:

0) The use case that this addresses is when JDK_IMPL=ibm versus JDK_IMPL=openj9 or hotspot, as the IBM SDK is built on an earlier OS version (for zLinux and AIX).  This means for example in a mixed build farm running ibm and openj9 tests, that an openj9 sdk landing on an AIX6.1 server will not run (as its been build on AIX7).  It is unlikely that we will correct this build discrepancy in the AdoptOpenJDK openj9 builds for those platforms (due to open availability of early enough CentOS and AIX versions).  So, we will assume that this is not a temporary condition (of ibm vs openj9 builds not running on exact same hardware)  FYI @sxa555 

1) One way to keep the same API, as in to pass a single LABEL rather than adding ability to append a partial label (to handle a case where that label may deviate at a particular server) is to create a groovy sharedlib that can be called by pipelines hosted in any git repo, running on any Jenkins server) to figure out what label is appropriate to use given a set of inputs  (that include platform, server, impl, etc).  jenkins-helper repo exists for this, but it is not commonly used and may not be what we want

2) While I am still loathe to keep adding more parameters especially at the rate of which we are doing, I can think of one other potential use case of this feature request.  The case where a certain test needs a certain machine capability.  We can add a clause in the test to skip a test if it does not find a certain machine capability, but this does not help us guarantee that these tests ever 'land' on a machine with the capability and get run.  One way to handle this is to make sure those capabilities are captured in the label schema, and create jobs of tests that require certain capability to append the extra label to ensure tests land on the right machines and get executed.

Will wait to discuss with @llxia , as we had planned to create a function that does this mapping already (rather than keep adding more files for each platform) and that work is related to this.

**Comment by smlambert** [comment]
Given all the discussion and the 2 extra use cases for appending a LABEL_ADDITION, we should add the extra explicit parameter.

Likely put a moratorium on any extra parameters after this, for any new ones, we will look at existing ones can be removed (because they are not used often).
