### ISSUE TITLE
Reinstate java/math/BigInteger/largeMemory/SymmetricRangeTests.java when fixed at openjdk

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1687]
This should be kept open until https://bugs.openjdk.java.net/browse/JDK-8241097 is fixed.

The test java/math/BigInteger/largeMemory/SymmetricRangeTests.java needs reinstating to run on openj9 releases when the required test change described in https://bugs.openjdk.java.net/browse/JDK-8241097 is made.

**Comment by smlambert** [comment]
We do not actually want to keep duplicate issues or "reinstate" issues open in this repo.  Once an issue is raised to the appropriate repo where a fix needs to take place, we should update the excludes file with its URL and close the openjdk-tests one.  

It is sufficient to ensure that the excludes file references URL to the upstream defect.

Right now those excludes links get manually checked, but the reason we insist on the full URL is used, is that we have the eventual intention to automate the reinclusion, based on the the state of the linked issue and whether an automated rerun of the test passes.

So, https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk14-openj9.txt#L150 can be updated to point to https://bugs.openjdk.java.net/browse/JDK-8241097 instead of the now closed [openj9 bug](https://github.com/eclipse/openj9/issues/8728), and https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk14-openj9.txt#L152 should be removed (as its a duplicate entry to line 150) at which point this issue should be closed.

I believe there are some other issues in this repo that can be similarly closed (where there is an upstream bug reported, exclude file updated to point to the real issue and openjdk-tests issue closed).

**Comment by lumpfish** [comment]
OK, I've created https://github.com/AdoptOpenJDK/openjdk-tests/pull/1689.
I've pointed all releases at the same issue url for now because there are not yet any issues for backporting the test fix to releases other than HEAD.

**Comment by karianna** [comment]
@lumpfish merged that PR, can we close this?

**Comment by lumpfish** [comment]
Yes, closing

**Comment by smlambert** [comment]
Thanks @lumpfish !
