### ISSUE TITLE
TreeBinAssert.java fails on Coretto

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1866]
**Describe the bug**
TreeBinAssert.java fails against a build of Coretto's jdk11.

This bug was fixed upstream in openjdk11 by [this](https://bugs.openjdk.java.net/browse/JDK-8240655) code change, however this change did not get imported into Corretto (despite its age).

Could this be a bug with Coretto's merge system?

Coretto bug raised [here](https://github.com/corretto/corretto-11/issues/117).

**To Reproduce**
https://trss.adoptopenjdk.net/output/test?id=5efea4b42e55416417c06c11

**Expected behavior**
The test should pass.

**Additional context**

**Comment by smlambert** [comment]
We have already had another case where the test code we take is not the correct version with the repo that is used to build Corretto.  In order to be able to match the repo, the build pipeline should pass the SHA of the jdk11u repo to test pipelines, otherwise we have to make the assumption that its built from tip.

I believe this is the case, and that the fix would be to update how corretto build pipeline is called. 

See https://github.com/AdoptOpenJDK/openjdk-build/issues/1674

**Comment by adamfarley** [comment]
[Here](https://github.com/corretto/corretto-11/issues/117) the Coretto team assert that "Our master and develop branches are still based on 11.0.7, but after 11.0.8 releases, they will be updated (and this error will be fixed)"

So I don't expect this issue to go away until after the release.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1876 has addressed the issue with matching test material to jdk repo.
