### ISSUE TITLE
test pipeline Timeout not observed if downstream jobs still running

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#1991]
**Describe the bug**
See: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux/9/console
This Test pipeline job has a Stage timeout of 10hrs, and it launches 10+ sanity.external sub-jobs each of which have 10hr timeouts themselves. The top level stage 10hr Timeout has been hit, but it does not terminate because several of the downstream test jobs are still waiting/running.

Looking at the downstream jobs: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux_openliberty-mp-tck/
Queued for 7hrs and has been running for 4+hrs.
The Timeout figure is set on the Test "stage", and thus the Queued time is not included, perhaps the Timeout should include the Queue time? or alternatively maybe the Test "stage" timeout should not be as big as 10hrs?

**To Reproduce**
Nightly jdk8 zLinux build.

**Expected behavior**
The Test pipeline should terminate after 10hrs.

**Screenshots**

**Additional context**

**Comment by sxa** [comment]
I'm not sure from this description what the issue is. What is blocking things? Is it just availability of machines? I'm not sure queued time should be included in the timeout for terminating jobs if it's just because all available machines are in use.

**Comment by smlambert** [comment]
As discussed today, our test timeout does NOT (and should NOT) include queue time (since that is either a reflection of too few machines, poor scheduling or a combo of both).  

A running time of 4hrs is not necessarily concerning to me.  And because someone has been manually aborting all of the runs, I can not say what is the expected execution time for this test from looking at Jenkins:
<img width="807" alt="Screen Shot 2020-10-05 at 10 20 20 AM" src="https://user-images.githubusercontent.com/2836948/95091509-8d756500-06f4-11eb-87bd-8bab24fc42a0.png">

In none of the cases shown above (for [openliberty-mp-tck](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.external_s390x_linux_openliberty-mp-tck/)), have we actually hit the 10 hr execution time (since its the sum of Setup + Build + Test + Post steps, and does not include Queue).

**Comment by andrew-m-leonard** [comment]
as discussed we will address the resource issue
