### ISSUE TITLE
jdk11 Hotspot zLinux tests take too long to run...

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-tests#2051]
jdk11 Hotspot zLinux:
- sanity.external 7Hrs **Bogus: caused by sub-parallel job Queue time**
- extended.openjdk 6Hrs

**Comment by andrew-m-leonard** [comment]
### extended.openjdk:

jdk_custom_0 : <1min
jvm_native_sanity_0 : <1min
jvm_compiler_0 : 36mins
runtime_nestmate_0 : <1min
jdk_awt_0 : 2hrs47mins
jdk_beans_0 : 8mins
jdk_io_0 : <1min
jdk_other_0 : 3mins
jdk_net_0 : 26mins
jdk_nio_0 : 6mins
jdk_security1_0 : 2mins
jdk_security2_0 : 2mins
jdk_security3_0 : 22mins
jdk_security4_0 : 3mins
jdk_text_0 : 1min
jdk_time_0 : 1min
jdk_management_0 : 2mins
jdk_jmx_0 : 7mins
jdk_rmi_0 : 10mins
jdk_tools_0 : 6mins
jdk_jfr_0 : 10mins
jdk_instrument_0 : 2mins
jdk_jdi_0 : 8mins
build_0 : <1min
jdk_imageio_0 : 4mins
jdk_client_sanity_0 : 19mins
jdk_security_infra_0 : 7mins
jdk_native_sanity_0 : <1min
jdk_2d_0 : 15mins
jfc_demo_0 : <1min

**Comment by sxa** [comment]
@andrew-m-leonard Have you compared that with the extended.openjdk on other platforms - it looks like this is about double - do the AWT tests elsewhere take as long?

**Comment by sxa** [comment]
JDK11/JDK11/J9 takes 5h30 so I don't think singling out HotSpot here as "too long" is appropriate:
 https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_extended.openjdk_s390x_linux/

**Comment by smlambert** [comment]
6hrs to run extended.openjdk (7200+ testcases) for Hotspot is fine, I am not too concerned with this length of time (well below our 10hr bailout time), there is nothing that stands out as problematic (longest running is [java_awt_Window_ShapedAndTranslucentWindows_StaticallyShaped](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_s390x_linux/8/testReport/java_awt_Window_ShapedAndTranslucentWindows_StaticallyShaped/) at 8 min 31 sec, with some other jdk_awt at 3-5min and most other testcases running in under 1 min.  Feel free to look at any individual test case source code to see what it does to justify a multi-minute run (and perhaps suggesting/contributing optimizations upstream to openjdk if you find them).

Remembering also that newly added targets, including those in extended.openjdk are currently untriaged.  For OpenJ9 runs, some openjdk tests are not valid (and we still have to go through each and permanently exclude ones that are not applicable to the impl).  

Also of note, failing tests often take a very long time, as they have a timeout factor that they may retry and wait around on...

Exemplified by the JMX failures from the link in https://github.com/AdoptOpenJDK/openjdk-tests/issues/2051#issuecomment-726689371:
<img width="1314" alt="Screen Shot 2020-11-13 at 8 18 20 AM" src="https://user-images.githubusercontent.com/2836948/99090960-3a1cef00-259d-11eb-9ea8-223da45dc00c.png">
which take that long due to failing then sitting waiting on jtreg timeout to countdown.


sanity.external tests are run in parallel (so that each individual application is run in its own job).  As noted (in the triggering language of 'bogus'), running in separate jobs means waiting in line for resources.  Each sub-jobs execution time is not very long, if there was no queue.  Addressing the jdk8 hotspot on s390x should alleviate the wait on these resources.

I will be closing this issue as 'wont fix', but its noted as part of the EPIC execution time & schedule issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/2037.
