### ISSUE TITLE
MiniMix_5min_0 FAILED in Test_openjdk16_hs_extended.system_ppc64_aix and all other platforms

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2150]
The recently added MiniMix_5min test target fails consistently against hotspot.   Need to determine why and fix (or disable target temporarily).

**Test Info**
Test Name: MiniMix_5min_0
Test Duration: 1 min 47 sec
Machine: build-osuosl-aix71-ppc64-1
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5ff71bf62bad78506603ace1

**Build Info**
Build Name: Test_openjdk16_hs_extended.system_ppc64_aix
Jenkins Build start time: Jan 07 2021, 12:01 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.system_ppc64_aix/10/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5ff7180b2bad7850660383c2

**This test has been failed 10 times since Dec 28 2020, 11:26 pm**
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.system_ppc64_aix/1/

The test failed on machine build-osuosl-aix71-ppc64-1 4 times 
The test failed on machine test-ibm-aix71-ppc64-2 2 times 
The test failed on machine test-osuosl-aix72-ppc64-2 3 times 
The test failed on machine test-osuosl-aix71-ppc64-1 1 times 

----------

**Test Info**
Test Name: MiniMix_5min_0
Test Duration: 2 min 3 sec
Machine: test-ibmcloud-rhel7-x64-1
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5ff71a6b2bad78506603a076

**Build Info**
Build Name: Test_openjdk16_hs_extended.system_x86-64_linux
Jenkins Build start time: Jan 06 2021, 10:39 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.system_x86-64_linux/11/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5ff717d72bad785066038347

**This test has been failed 10 times since Dec 28 2020, 11:10 pm**
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.system_x86-64_linux/2/

The test failed on machine test-ibmcloud-rhel7-x64-1 2 times 
The test failed on machine test-ibmcloud-ubuntu1604-x64-1 1 times 
The test failed on machine test-packet-ubuntu1604-x64-3 2 times 
The test failed on machine test-godaddy-debian8-x64-1 1 times 
The test failed on machine test-godaddy-ubuntu1604-x64-1 1 times 
The test failed on machine test-packet-ubuntu1604-x64-2 1 times 
The test failed on machine test-godaddy-centos7-x64-2 1 times 
The test failed on machine test-godaddy-ubuntu1604-x64-2 1 times

FYI @Mesbah-Alam @lumpfish

**Comment by Mesbah-Alam** [comment]
https://trss.adoptopenjdk.net/output/test?id=5ff71a6b2bad78506603a076 - this failure is related to https://github.com/eclipse/openj9/issues/11607.

We have a [fix](https://github.com/AdoptOpenJDK/openjdk-tests/pull/2151) for this .

**Comment by Mesbah-Alam** [comment]
Recap of work done in https://github.com/AdoptOpenJDK/openjdk-tests/pull/2151 which is relevant to this issue: 

`MiniMix_5min` test failed with `InaccessibleObjectException` on OpenJ9 jdk16. We had to add `--add-opens java.base/java.lang=ALL-UNNAMED` to the command line to get it working.  

However, running the test on HotSpot revealed a second `InaccessibleObjectException` error, for which we had to add `--add-opens java.base/java.io=ALL-UNNAMED` to the command line. These two `--add-opens` have been delivered via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2151. 

**Note**: Although https://github.com/AdoptOpenJDK/openjdk-tests/pull/2151 made the `InaccessibleObjectException` error go away from the [hotspot](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5883/console) run, the test still failed with a different issue (a behaviour that's different than OpenJ9) . In order to get `MiniMix_5min` to pass on HotSpot, we may have to exclude the failing sub-test. See discussion [here](https://github.com/AdoptOpenJDK/openjdk-tests/pull/2151) for more info.

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2151 and https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/390 together have caused the MiniMix load to start passing in JDK16 Hotspot builds: 

https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.system_ppc64_aix/13/
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.system_x86-64_linux/14/

@ShelleyLambert - can we mark this issue resolved at this point?

**Comment by smlambert** [comment]
thanks @Mesbah-Alam, yes, closing this issue as resolved!  (btw, please tag @smlambert if you want my quick attention, it is my actively used github account).
