### ISSUE TITLE
Need to add macOS Arm64 spec

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-tests#2501]
As shown in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-arm64-hotspot_SmokeTests/8/console

```java
java.lang.AssertionError: Cannot find key PLATFORM: arm64_mac in PLATFORM_MAP
```

**Comment by gdams** [comment]
I've temporarily added `sw.os.osx hw.arch.arm64 ci.role.test` to the build machines until we have more hardware

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/55/console - will have to add some prints in the setup stage to understand why it (silently) fails...

**Comment by smlambert** [comment]
How to address this issue is to add a section in the [PLATFORM_MAP in the openjdk_tests](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests#L7) file for this platform, 

```
   'arm64_mac' : [
        'SPEC' : 'arm64_mac',
        'LABEL' : 'ci.role.test&&sw.os.osx&&hw.arch.arm64',
    ],
```

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).  Note: that you do not need to add yourself to a Contributors.md file as outlined in the detailed instructions.

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**Comment by gdams** [comment]
@ShelleyLambert looks like you were pointing it at the wrong job number, trying again here: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/61/console

**Comment by gdams** [comment]
Another test with `JDK_REPO` set correctly: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/63/console

**Comment by smlambert** [comment]
Great, Grinder/63 passed.  Though we still need to merge in a PR - those Grinders were running off of my branch, no PR created yet.

**Comment by gdams** [comment]
PR created here https://github.com/AdoptOpenJDK/openjdk-tests/pull/2509

**Comment by smlambert** [comment]
ha, ok thanks for the fix @gdams, but now you owe me a "[good first issue](https://github.com/orgs/AdoptOpenJDK/projects/2)" that can be offered to the 50+ Outreachy candidates.  ;)

**Comment by gdams** [comment]
@sophia-guo I was stupidely cross-compiling the x64 version.

An updated build shows the correct output:

```bash
System.getProperty('os.arch')=aarch64
```
