### ISSUE TITLE
Add system test repo specific fields to grinder job template 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#2519]
We need to add the following three system test repo specific fienls to grinder job template : 

|Field Name| Description| Default value | 
|--|--|--|
|ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH | Personal Adoptopenjdk/openjdk-systemtest repository owner:branch | AdoptOpenJDK:master|
|OPENJ9_SYSTEMTEST_OWNER_BRANCH|Personal eclipse/openj9-systemtest repository owner:branch | eclipse:master|
| STF_OWNER_BRANCH| Personal stf repo owner:branch| AdoptOpenJDK:master|

FYI @ShelleyLambert @llxia

**Comment by 2001asjad** [comment]
Hi can you please tell me more about this issue so that I can work on it like what files to look etc, @Mesbah-Alam @ShelleyLambert @llxia .
Thank You.
PS: I am an Outreachy applicant

**Comment by smlambert** [comment]
Hi @2001asjad - the changes required to address this issue is to add these parameters with their descriptions and default values (as mentioned in the table above) into the testJobTemplate file just after the [TKG_SHA parameter](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L227).  You can see based on the other parameters being set in this file the pattern to follow.  

If you want to take this issue, let me know and I will assign it to you.  Once you have a PR, we can help you test your changes at the ci.adoptopenjdk.net Jenkins server.

**Comment by 2001asjad** [comment]
Thank You @smlambert and yeah I definitely wanna work on this issue, please assign this to me.
Gonna update you soon with a PR.
Once again thank you so much for providing the info above.

**Comment by 2001asjad** [comment]
Made a PR, @smlambert can you please take a look. Eagerly waiting for your suggestions
