### ISSUE TITLE
Investigate/Implement slack notifications and github PR hooks etc in JenkinsFiles.

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-tests#32]
some activity in the Build/ansible/playbooks dir in openjdk-tests repo, is there an issue/enhancement that this work belongs to @bblondin so we do not duplicate/overlap effort?  example, we can add slack notification re: test builds directly from Jenkinsfiles for test build failure/success

**Comment by smlambert** [comment]
good reference: https://jenkins.io/blog/2016/07/18/pipline-notifications/

**Comment by smlambert** [comment]
Looking at this, wondering what is being asked.  We can add notifications when there are test failures.  It will create a lot of noise at the moment (due to excessive test failures - tests which we should consider excluding until fixes can be applied), but we can try it out and see what volume of notifications is useful.  As an example of too much noise, I find the auto-notifications in the infrastructure channel to not be useful, and in fact detrimental to finding any info there.

**Comment by karianna** [comment]
Agreed - this should only be switched on once we have an all green base line.

**Comment by smlambert** [comment]
This got turned on for all test builds, so i will close it.  We may want to have a flag on this capability so that we can easily disable it in the event of catastrophe, but I will capture that in a separate item.
