### ISSUE TITLE
Support personal openj9 repo and branch in Grinder

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#415]
We would like to allow user to provide personal OpenJ9 repo and branch for launching personal build (grinder). This will allow user to test their own test changes in OpenJ9 repo.

**Comment by smlambert** [comment]
#412 - let's you set to your Adopt/openjdk-tests branch, this extends the grinder feature so that if you are pulling in functional tests from the openj9 repo, you can pull in from your eclipse/openj9 branch (though by default, and currently it pulls the master).

There are ~20,000 functional tests in openj9.  In the future, we may be interested in running them in Adopt test runs.  For now, we will add this enhancement, so that people who are using the Adopt Jenkinsfiles for running their own testing can point to their own branch for those tests, if needed.

**Comment by llxia** [comment]
Change delivered. Close this issue.
