### ISSUE TITLE
Support tar.gz file as customized sdk in grinder

### ISSUE THREAD

**Issue by liqunl** [AdoptOpenJDK/openjdk-tests#443]
```
10:24:55 [OpenJ9-JDK8-win_x86-64_cmprssptrs-201811060922.tar.gz]
10:24:55   End-of-central-directory signature not found.  Either this file is not
10:24:55   a zipfile, or it constitutes one disk of a multi-part archive.  In the
10:24:55   latter case the central directory and zipfile comment will be found on
10:24:55   the last disk(s) of this archive.
10:24:55 note:  OpenJ9-JDK8-win_x86-64_cmprssptrs-201811060922.tar.gz may be a plain executable, not an archive
10:24:55 unzip:  cannot find zipfile directory in one of OpenJ9-JDK8-win_x86-64_cmprssptrs-201811060922.tar.gz or
10:24:55         OpenJ9-JDK8-win_x86-64_cmprssptrs-201811060922.tar.gz.zip, and cannot find OpenJ9-JDK8-win_x86-64_cmprssptrs-201811060922.tar.gz.ZIP, period.
10:24:55 The system cannot find the file specified.
```

**Comment by smlambert** [comment]
Note, this is only an issue for Window, which are currently using a temporary set of batch files.  The configuration of the machines needs to be updated so that we can use the shell scripts used by the other platforms that do support tar.gz.

Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/378

**Comment by sophia-guo** [comment]
All windows SDKs in adoptOpenJDK builds are zipped and have default naming convention like OpenJDK*.zip. My understand is that cross-platform programs are sometimes distributed as .tar.gz for the Unix version and .zip for the Windows version. Windows prefers .zip because that's the format it can handle out of the box. I recall @gdams has a comment about this?

**Comment by smlambert** [comment]
I do not believe we will change the behaviour of the script, as open builds use .zip format for Windows.  @liqunl - if you feel strongly that this is needed, please re-open this issue.

We should address the discrepancy between open/closed builds as a better solution.
