### ISSUE TITLE
Improve error handling for invalid SDK

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#468]
Currently if SDK is invalid (i.e., SDK does not get downloaded properly, or SDK URL is invalid) and wget does not return error, the program will proceed and fail at a later stage - test compilation. At that time, the error can be misleading. (i.e., `/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image//bin/java: Syntax error: word unexpected (expecting ")")`)

I think we should improve the error handling for invalid SDK. 
- make sure we can find java executable
- run a `java -version` to verify it is ok

If there is an error, then there is no point to proceed.

**Comment by sophia-guo** [comment]
#384 enhanced the SDK download error handling.
In AdoptOpenJDK builds function printJavaVersionString() is to check java -version. Only when it succeeds build SDK will continue and mark as succeed. 

It would be better for openj9 build to do same thing. 

BTW just realized that error in grinder build was caused by running arm32 sdk on arm64 platform as we currently do not have arm32 test machine.

**Comment by llxia** [comment]
Close this issue as we do not use wget anymore.
