### ISSUE TITLE
JCK11 test bringup

### ISSUE THREAD

**Issue by JasonFengJ9** [AdoptOpenJDK/openjdk-tests#488]
It appears there are specific settings for `JCK` levels such as https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L52.
Not sure if there are other places.

Can we bring up `JCK11` tests for coming `JDK11`?

**Comment by llxia** [comment]
The script should be updated to get JCK_VERSION from JAVA_VERSION, similar to https://github.com/AdoptOpenJDK/openjdk-tests/blob/ebef3ea96d7e2b937f463ef7d3e192f87d4bdb44/buildenv/jenkins/Jenkinsfile_personal#L129

We should only need to handle special case in the script, such as jck8b.
And JCK_VERSION should be a parameter, so that user can pass in their value.

**Comment by smlambert** [comment]
Fixed by #507
