### ISSUE TITLE
Directly use JTHarness or JTReg run JCK tests?

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#547]
Current JCK tests are running by stf framework, which depends on stf and openjdk-systemtest repo. Underlying stf is using JTHarness (using jtlite.jar). Under the current structure tests could be directly  defined by command by testcase in playlists.  Directly using JTHarness or JTReg could be more straightforward?

**Comment by smlambert** [comment]
Yes, I will prefer to remove the extra layer.  I have mentioned this in other issues, but thank you for creating this one where it can be addressed.  

Removing the layer also simplifies the build story, related: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/142 and allows for more direct access to updating the options to javatest, implication, changes to one repo instead of 2 (like those we need to generate alternate test output, for easier viewing of results on the private Jenkins server where JCKs run at AdoptOpenJDK).

**Comment by sophia-guo** [comment]
Close this as there are related issue opened in https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/142
