### ISSUE TITLE
Add label ci.role.test to Jenkins Pipelines and Test machines

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-tests#671]
We (OpenJ9) have a need to separate some build farm and test machines. Through discussion we have concluded and are proposing we add labels `ci.role.build` and `ci.role.test` to the appropriate machines and corresponding pipelines. We would encourage the Adopt-build Pipeline scripts to do the same, although not required as we have our own OpenJ9 build pipelines.

Steps to Implement:
- Add labels to machines
- Add labels to Pipelines
- Remove obsolete labels (if applicable)

**Comment by karianna** [comment]
I thought we already had a similar naming scheme...

**Comment by AdamBrousseau** [comment]
I believe this was partially implemented in AdoptOpenJDK/openjdk-infrastructure#93. From what I see, the current usage is:
- Build has not adopted the new label schema
- Test uses it partially (eg. `hw.arch.x86&&sw.os.linux` see [here](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_x86-64_linux#L2))

[Build machine](https://ci.adoptopenjdk.net/computer/build-cloudcone-ubuntu1604-x64-1/)
`build cloudcone hg linux ubuntu ubuntu16 ubuntu1604 x64 x86_64`
[Test machine](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/)
`hw.arch.x86 linux sw.os.linux sw.tool.docker test ubuntu x64`

The only reason tests don't hit the build machines at Adopt is because the build machines don't use the standard schema.

**Comment by smlambert** [comment]
Answering Martijn's question, we do use this schema for test machines, as I proposed in this branch https://github.com/smlambert/openjdk-infrastructure/blob/labels/docs/jenkinslabels.md, but we did not go as far as labelling build machines at adopt, because we still had folks that held off on agreement.  So we only applied these labels to test machines.  

I am happy to apply to all machines, as most of the disagreement was based on statements that are not actually an issue ('the labels are too long to type' - not really an issue, since mostly no one types them, they are in Jenkinsfiles and hardly ever manually entered).

**Comment by karianna** [comment]
I think cleaning the labels up is a good idea. We can always revisit how we use labels later, but we should be consistent to start with.  @smlambert I say go ahead (but perhaps summarise what's going to change before you apply it).

**Comment by smlambert** [comment]
Will do, I will update the doc in my openjdk-infrastructure branch and create a PR to summarize it.  👍

**Comment by smlambert** [comment]
I've already updated the test machines with the proper labels.   

At present, we do not need to update the build machine labels as the build / test machines are separate, and the build scripts do not use the schema at present.
