### ISSUE TITLE
Update regression tests story with openj9 jdk

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#739]
Current regression tests are using AdoptOpenJDK/jdk** mirror against both hotspot and openj9 JDK. However Openj9 extension is mirrored using different strategies on different schedules from AdoptOpenJDK/jdk** mirror. This causes mis-matched problem with product code and test code for Openj9. 

Discussion in the Slack suggested to clone the tests from the same repo that the build under test was from.  https://adoptopenjdk.slack.com/archives/C5219G28G/p1543939103005200

**Comment by sophia-guo** [comment]
Note mis-match could still happen for nightly running (master tip) as tests are triggered later than jdk builds. That is there will be gap between production code and test code if there is a new commit to test during jdk building. Though according to history jdk test repo doesn't update very often.

If this mis-match is unacceptable then we will need Build strip passing in jdk repo name and build sha parameter. So test and production code can be always consistent.  

FYI @ShelleyLambert

**Comment by llxia** [comment]
IMO, JDK build and test should be always consistent. The upstream build should trigger test build with the repo and sha. Otherwise, if mismatch happens, it is very hard to debug.

In openj9 build, test builds are triggered with the repo and sha parameters:
https://github.com/eclipse/openj9/blob/e278b3a0b605069a2eccc60bf4d3df7eb934bc56/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All#L195

https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/107/parameters/

**Comment by smlambert** [comment]
I agree with @llxia, we should attempt to match exactly where possible to avoid debugging strange/opaque skew issues at some later time.

**Comment by sophia-guo** [comment]
Fixed by a few different PRs .
