### ISSUE TITLE
Enable macos test build 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#77]
Now that we have some macs for testing, we can enable a test build (https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_macos/) that will be triggered to run all the tests upon successful completion of the image build (https://ci.adoptopenjdk.net/job/openjdk_build_x86-64_macos/).

**Comment by gdams** [comment]
@smlambert can you ensure that the test tag is used, this is currently running on the build mac

**Comment by sophia-guo** [comment]
Jenkins build got "wget: command not found"
Login in as Jenkins wget works fine. "Which wget" will get this wget is a softlink. Using absolute path of wget in jenkins build will also work.

@bblondin  we need to update "Configure System" and add environment variables to update PATH environment to include  path /usr/local/Cellar/wget/1.19.1_1/bin/, probably do the same thing for all slave machines.

**Comment by gdams** [comment]
okay so for some reason jenkins doesn't seem to have `/usr/local/bin/` in the path. That's why wget is not getting detected

**Comment by bblondin** [comment]
wget is on the path for Jenkins:

sh-3.2# su - jenkins
DXU773:~ jenkins$ which wget
/usr/local/bin/wget

Error: /Users/jenkins/workspace/openjdk_test_x86-64_macos/openjdk-test/get.sh: line 33: wget: command not found

inside get.sh you should have code that sets the path: ie.
```
if [[ "$(uname)" = Darwin ]] ; then
        export PATH=$PATH:/usr/local/bin/
fi
```

I see that you have attempted to call wget directly from its real path in get.sh (/usr/local/Cellar/wget/1.19.1_1/bin/wget http://download.forge.ow2.org/asm/asm-5.0.1.jar) for one of the wget calls. if you are going to do this it should be a call to /usr/local/bin/ as the version of wget (and other tools) will change in the future.

**Comment by sophia-guo** [comment]
I would prefer to set this PATH by environment variable instead of setting it in the script file. The reason is this is a jenkins environment setting, which should not be handled by shell script. The advantage is in this way it will not be needed to be exported for each test build. 

Login in as jenkins wget is on the path for Jenkins. However if you put "which wget" in script shell and trigger the build by jenkins interface you will see "no wget command". I believe login in as jenkins the environment variables is different from the jenkins system properties from Manage Jenkins from UI? Could you check the System properties using Manage Jenkins?

Calling wget directly from its real path in get.sh (/usr/local/Cellar/wget/1.19.1_1/bin/wget http://download.forge.ow2.org/asm/asm-5.0.1.jar)  is only to help to figure out what is the issue.

**Comment by bblondin** [comment]
ok added to the two test macs

**Comment by gdams** [comment]
@smlambert can this be closed now?

**Comment by smlambert** [comment]
Yes, closed.  Mac test builds are running to completion: https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_macos/
