### ISSUE TITLE
thirdparty tests with docker cp command will leave test result on disk

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#918]
thirdparty tests with docker cp command after  '$(TEST_STATUS); ' will leave test result on disk even if with KEEP_REPORTDIR=false, which could increase the size of test result jar, i.e. test result artifacts.

```
		<command>docker run --name elasticsearch-test $(EXTRA_DOCKER_ARGS) adoptopenjdk-elasticsearch-test:latest; \
			$(TEST_STATUS); \
			docker cp elasticsearch-test:/elasticsearch/core/build/reports/testJunit $(REPORTDIR)/external_test_reports; \
			docker cp elasticsearch-test:/elasticsearch/modules/transport-netty4/build/reports/testJunit $(REPORTDIR)/external_test_reports; \
			...

```

**Comment by Mesbah-Alam** [comment]
HI @sophia-guo, have you discovered the reason why KEEP_REPORTDIR=false would not cause the cleanup to remove test result? Does it work if `docker cp` happens before $(TEST_STATUS)? 

Note that the $(TEST_STATUS) step was moved immediately after the `docker run` command (in all external test playlists) due to : https://github.com/AdoptOpenJDK/openjdk-tests/issues/620#issuecomment-429432247

**Comment by smlambert** [comment]
is this issue still relevant?

**Comment by sophia-guo** [comment]
Yes, as  external tests do the `docker cp` after $(TEST_STATUS) test result will be kept at  $(REPORTDIR) and consequently be a part of test result artifacts. Though iIt won't be an issue for jenkins slave as jenkins can do its own cleanup.

**Comment by sophia-guo** [comment]
Close it as it's not an issue with external updated its structure.
