### ISSUE TITLE
function and system tests under third party container tests are grouped as either functional or system instead of external

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#919]
Function and system test under third party container tests are grouped as either functional or system instead of external, is it expected?

**Comment by smlambert** [comment]
@llxia and I are aware of this.  We have not corrected it, because once we do these tests will run, and since all tests run in sequence, we will hit the time out limit (10hrs) and abort.

This should get fixed once we break up these external tests to run individually (each subdir, like scala, elasticsearch, derby, etc running in its own job).

**Comment by smlambert** [comment]
I see this has been [corrected](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/functional-test/playlist.xml#L27) for all targets, so closing.
