### ISSUE TITLE
openjdk-tests build builds openjdk-systemtest multiple times

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#978]
I have noticed that a build of openjdk-system test takes much longer when built via the openjdk-tests builds scripts than via the openjdk-systemtest build script (make build).

This seems to be why:
1. In openjdk-tests/systemtest/build.xml contains a target
```
	<target name="build" depends="dist,common_build">
		<property name="common_build.executed" value="true" />
		<subant target="" inheritall="true">
			<fileset dir="." includes="*/build.xml" />
		</subant>
	</target>
```
2. The dependent target common build is in openjdk-tests/systemtest/common.xml and says:
```
	<!-- To make sure common_build target only excute once, the common_build target runs only if common_build.executed value is not set -->
	<target name="common_build" depends="build-dependencies" unless="common_build.executed">
		<echo message="target common_build is called....." />
	</target>
```
3. The dependent target build-dependencies is also in openjdk-tests/systemtest/common.xml
```
	<!-- target to build all projects in the repository.  -->
	<!-- dir must be set on the ant task otherwise the basedir property is not set to a new value in the subant task. -->
	<!-- Also make sure stf is built -->
	<target name="build-dependencies" depends="configure_systemtest">
		<if>
			<contains string="${JVM_VERSION}" substring="openj9"/>
			<then>
				<ant antfile="${SYSTEMTEST_ROOT}/openj9-systemtest/openj9.build/build.xml" dir="${SYSTEMTEST_ROOT}/openj9-systemtest/openj9.build" inheritAll="false">
					<property name="java.home" value="${env.JAVA_HOME}"/>
				</ant>
			</then>
			<else>
				<ant antfile="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build/build.xml" dir="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build" inheritAll="false">
					<property name="java.home" value="${env.JAVA_HOME}"/>
				</ant>
			</else>
		</if>
		<antcall target="common_dist" inheritall="false" />
	</target>
```
Running the openjdk-systemtest/openjdk.build/build.xml builds all the tests in the openjdk-systemtest repository.

4. After executing build-dependencies the original build target executed any other build.xml files it can find under openjdk-tests/systemtest.  Each on of those also has a dependency on the common-buil;d target - e.g. 
```
	<target name="build" depends="init, common_build">
		<echo message="xxxxxxxxx running build in daaLoadTest/build.xml"/>
		<copy todir="${DEST}">
			<fileset dir="." includes="*.mk,*.xml"/>
		</copy>
	</target>
```

5. The common_build target has tried to guard itself from multiple executions by setting the common_build.executed property.  However, if / unless attributes are only evaluated after dependencies have been executed, so this does not work (e.g. see https://stackoverflow.com/questions/4014094/in-what-order-are-ant-targets-if-and-depends-evaluated).  As a result build-dependencies executes for each build.xml file under openjdk-tests/systemtest. making the build about 10 times slower than it should be.
```
	<!-- To make sure common_build target only excute once, the common_build target runs only if common_build.executed value is not set -->
	<target name="common_build" depends="build-dependencies" unless="common_build.executed">
		<echo message="target common_build is called....." />
	</target>
```

6. This can be fixed by guarding the build-dependencies target with the common_build.executed property directly.

7. As an aside, it is not clear to me what the 'subant' calls to the build.xml files are meant to achieve, since the common build already builds all the openjdk-systemtest test cases. @Mesbah-Alam - any insights?

**Comment by llxia** [comment]
> As an aside, it is not clear to me what the 'subant' calls to the build.xml files are meant to achieve, since the common build already builds all the openjdk-systemtest test cases.

This structure is set up to support the running test for parent dir. When running the test from parent dir (i.e., systemtest), we use `subant` to call build.xml in each subdir. Each build.xml in the subdir contains setup specifically for this subdir. 

For the initial separation, we do not have much in each subdir build.xml in systemtest. The plan is to break common.xml. So each subdir build.xml only needs to call its relevant targets.

**Comment by Mesbah-Alam** [comment]
@llxia, 

I have also noticed the extra/unusually lengthy time (2h45m seen in aarch64 machines) it takes for system tests to finish the "compilation" step. 

Here are my two cents: 

1) systemtest/build.xml's "build" target is invoking systemtest/common.xml's "common_build" for the first time, which is ending up invoking common.xml's "build-dependencies" target, which is invoking `openj9.build/build.xml` or `openjdk.build/build.xml` - resulting in compilation of all required systemtest sources. 

2) Then going back to systemtest/build.xml, the sub-ant targets are calling build.xml of each of the system test folder (e.g. mathLoadTest/build.xml etc) -- who themselves are calling common.xml's "common_build" target -- which, I think the assumption is that, will not do anything since `common_build.executed` is set to true by this time via step (1). -- I think what Simon is saying is, the way the code is set up a.t.m, this is not working, and "common_build" (therefore "build-dependencies") is being invoked and the entire system test source is being built once for each system test folder.  

In common.xml we have : 
```
<target name="common_build" depends="build-dependencies" unless="common_build.executed">
		<echo message="target common_build is called....." />
	</target>
```

Instead of this, if we move the `unless="common_build.executed"` condition inside the  `build-dependencies` target itself, we'd have the desired result, which is partially done in : https://github.com/AdoptOpenJDK/openjdk-tests/pull/979/files

**Comment by llxia** [comment]
yes, as Simon pointed out, if / unless attributes are only evaluated after dependencies have been executed. The current code does not stop predecessors to be executed.
